@startuml Kairosユースケース一覧
title Kairosユースケース一覧
left to right direction

actor "利用者" as User
note bottom of User : アクセスは主にスマホ、PCを想定
actor "定期実行プロセス" as AutoProcess
note top of AutoProcess : 利用者の持つ端末やスマホで実行されるプロセス

rectangle "Kairos(勤怠管理システム)" {
    package "認証機能" {
        (ログイン) as Login
        (ログアウト) as Logout
    }
    package "勤怠機能" {
          (勤怠表一覧の閲覧) as ViewReportList
          (勤怠表の閲覧) as ViewReport
          (勤怠表修正) as EditReport
          (勤怠表登録) as RegisterReport
          (勤怠表自動作成) as AutoCreateReport
    }
    package "打刻機能" {
        (位置情報登録) as RegisterLocations
    }
    package "管理機能" {
        (勤怠ルール管理) as ManageWorlRules
        (勤怠表自動生成ルール管理) as ManageReportCreationRules
    }
}

User --> Login
User --> Logout
User --> ViewReportList
User --> ViewReport
User --> EditReport
User --> RegisterReport
User --> ManageWorlRules
EditReport .> AutoCreateReport : include
RegisterReport .> AutoCreateReport : include
User --> ManageReportCreationRules
AutoProcess --> RegisterLocations

@enduml