@startuml Kairos画面遷移
title Kairos画面遷移

state "ログイン" as LoginView {
    LoginView : Entryntry / 初期表示
    LoginView : Login / ログイン
    LoginView -> LoginView : ログイン失敗
}
state "設定" as SettingsView {
    SettingsView : Entryntry / 初期表示
    SettingsView : OpenWorkRuleSettings / 勤怠設定
    SettingsView : OpenAutoCreateSettings / 勤怠表自動作成設定
}
state "勤怠表一覧画面" as ReportListView {
    state "勤怠表一覧" as ReportListView_Normal {
        ReportListView_Normal : Entryntry / 初期表示
        ReportListView_Normal : OpenMenu / メニュー表示
        ReportListView_Normal : OpenReport / 勤怠年月選択
    }
    state "メニュー" as ReportListView_Menu {
        ReportListView_Menu : logout / ログアウト
        ReportListView_Menu : OpenSettings / 設定
        ReportListView_Menu : CloseMenu / メニュー閉じる
    }

    [*] --> ReportListView_Normal : 初期表示
    ReportListView_Normal --> ReportListView_Menu : メニュー表示
    ReportListView_Menu --> ReportListView_Normal : メニュー閉じる
}
state "勤怠表画面" as ReportView {
    state "勤怠表" as ReportView_Normal {
        ReportView_Normal : Entryntry / 初期表示
        ReportView_Normal : OpenMenu / メニュー表示
        ReportView_Normal : EditRow / 勤怠編集
        ReportView_Normal : SaveReport / 保存
    }
    state "メニュー" as ReportView_Menu {
        ReportView_Menu : Logout / ログアウト
        ReportView_Menu : OpenSettings / 設定
        ReportView_Menu : CloseMenu / メニュー閉じる
    }

    [*] --> ReportView_Normal : 初期表示
    ReportView_Normal --> ReportView_Menu : メニュー表示
    ReportView_Menu --> ReportView_Normal : メニュー閉じる
    ReportView_Normal --> ReportView_Normal : 勤怠編集\n保存
}

[*] -r-> LoginView : アクセス
LoginView --> ReportListView : ログイン成功
ReportListView_Normal --> ReportView : 勤怠年月選択
ReportListView_Menu --> LoginView : ログアウト
ReportListView_Menu --> SettingsView : 設定
ReportView_Menu --> SettingsView : 設定
ReportView_Menu --> LoginView : ログアウト
@enduml